version: '3'

services:
  db:
    container_name: user-service-pgdb
    image: postgres:alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
  app:
    container_name: user-service-app
    build:
      context: .
    env_file:
      - .dev.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:3000
    command: npm run start:dev
    depends_on:
      - db
    restart: always

volumes:
  pgdata:
